index: package
	cd ../chart-index && helm repo index .

package:
	cd ../chart-index && helm package ../chart/kubeless-pulsar-trigger
	cd ../chart-index && helm package ../chart/kubeless-pulsar-trigger-crd
