---
apiVersion: kubeless.io/v1
kind: PulsarTrigger
metadata:
  name: tg1
  namespace: default
spec:
  ## Topic: persistent://public/default/mytopic
  pulsar:
    namespace: default
    topic: mytopic
    broker: pulsar://pulsar.lab.tjpr.jus.br:6650
    auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZXJ0LXdhdGNoIn0.KOzPDoJNqZlv7KvGYo6siiS7fcKykuHiqvivxuw-NWA
  kubeless:
    namespace: default
    function: hello
    port: 8080
  deployment:
    metadata:
      labels:
        l1: v2
    spec:
      template:
        spec:
          containers:
            - resources:
                limits:
                  cpu: 2
                  memory: 2Gi
