---
apiVersion: kubeless.io/v1
kind: PulsarTrigger
metadata:
  name: tg1
  namespace: default
spec:
  topic-namespace: tpns
  topic-name: tpname
  kubeless-handler: hello
  kubeless-function: world
  kubeless-function-namespace: kns
  deployment:
    spec:
      template:
        metadata:
          annotations:
            a1: v2
