---
apiVersion: kubeless.io/v1
kind: PulsarTrigger
metadata:
  name: tg1
  namespace: default
spec:
  pulsar:
    topic: persistent://public/default/mytopic
    broker: pulsar://pulsar.addr:6650
    auth-token: nnn
  kubeless:
    function: http://hello.default:8080
  deployment:
    metadata:
      labels:
        l1: v2
    spec:
      template:
        spec:
          containers:
            - resources:
                limits:
                  cpu: 2
                  memory: 2Gi
