---
apiVersion: kubeless.io/v1
kind: PulsarTrigger
metadata:
  name: tg1
  namespace: default
spec:
  ## Topic: persistent://public/default/mytopic
  pulsar-topic-namespace: default
  pulsar-topic-name: mytopic
  pulsar-broker: pulsar://pulsar.lab.tjpr.jus.br:6650
  pulsar-auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZXJ0LXdhdGNoIn0.KOzPDoJNqZlv7KvGYo6siiS7fcKykuHiqvivxuw-NWA
  kubeless-function: hello
  kubeless-function-namespace: default
  deployment:
    spec:
      template:
        metadata:
          annotations:
            a1: v2
