## Dispatcher Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    created-by: kubeless-pulsar-trigger
  name: REPLACED_AT_RUNTIME
  namespace: default
spec:
  selector:
    matchLabels:
      created-by: kubeless-pulsar-trigger
  template:
    metadata:
      labels:
        created-by: kubeless-pulsar-trigger
    spec:
      replicas: 1
      ## container template is a separate yaml
      containers: []
