{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeless-pulsar-trigger.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeless-pulsar-trigger.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeless-pulsar-trigger.labels" . | nindent 4 }}
  name: {{ include "kubeless-pulsar-trigger.serviceAccountName" . }}
rules:
- apiGroups:
  - "kubeless.io"
  resources:
  - pulsartriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubeless-pulsar-trigger.labels" . | nindent 4 }}
  name: {{ include "kubeless-pulsar-trigger.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeless-pulsar-trigger.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeless-pulsar-trigger.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- end -}}
